### ISSUE TITLE
[2] Connect VVA - Implement getDocumentList

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/connect_vva#1]
Tech Notes: 
The `getDocumentList()` will return all documents and we need to filter restricted documents for our application.  We can filter restricted documents based on the values returned for the property `rstrcdDcmntIn`.  For restricted, `rstrcdDcmntInd` will have a value of `Y` (no quotes), and for non-restricted, `rstrcdDcmntInd` will have a value of `N` (no quotes) or null or empty string. Additionally, all IRS/SSA Verification, IVM, and Fiduciary categorized documents must be filtered out.  The `dcmntTypeLupId` will be used to identify these types of documents.

Filtering will be done at the application level.

**Comment by aroltsch** [comment]
[Document List for Caseflow - Master.Document.Type.Categories.August.2016_Restricted_Documents_w_others_that_must_remain_restricted_also.xlsx](https://github.com/department-of-veterans-affairs/connect_vva/files/983586/Document.List.for.Caseflow.-.Master.Document.Type.Categories.August.2016_Restricted_Documents_w_others_that_must_remain_restricted_also.xlsx)

**Comment by kierachell** [comment]
## Successfully finds documents for existing claims
```
[12] pry(main)> doclistres.count
=> 942
```

## Error unclear for non-existent claims:
```
[13] pry(main)> doc_list_service.get_by_claim_number("844610815")
NoMethodError: undefined method `map' for nil:NilClass
from /Users/vhaisavovka/Caseflow/connect_vva/lib/vva/services/document_list.rb:11:in `get_by_claim_number'
```

**Comment by kierachell** [comment]
Working claim numbers:
```
 "123123123",
  "234234234",
  "345345345",
  "456456456",
  "567567567",
  "678678678",
  "789789789",
  "987987987",
  "654654654"
```
Still looking for more

**Comment by kierachell** [comment]
Some document IDs come as `N`:
```
OpenStruct document_id="N", restricted=false, type_id="10", type_description="UNKNOWN", format="PDF", source="P8", jro="459", ssn="222222222"
```

**Comment by aroltsch** [comment]
@kierachell I have added error handling for invalid claim numbers. As far as this error `Unable to resolve '372_DS',  I think we can ignore it for a moment. Once we get access to their test environment, we will do more thorough testing.

**Comment by kierachell** [comment]
According to @nikitarockz we might get access to real Test environment tomorrow.

**Comment by kierachell** [comment]
**PASSED**

Working in new test environment
