### ISSUE TITLE
OpenSSL - set the cipher to NOT use DH key exchange.

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/connect_vva#13]
Details:
We notice that during SSL handshake with VVA systems, VVA server returns Diffie Hellman key that is too small (768 bit key). As of last week Caseflow systems started using OpenSSL 1.1.0 version which failed SSL handshake with VVA system. Newer versions of OpenSSL require 2048 bit Diffie Hellman key. As a result, we had to downgrade Caseflow systems to OpenSSL 1.0.1k (released in 2015) to maintain compatibility with VVA. This is a significant security vulnerability for both applications. If the server's DH group is too weak such as 768 bit key, an attacker can launch an active attack to take over the connection, or simply passively eavesdrop on the wire. 

AC:
Set the cipher to use RSA key exchange

**Comment by kierachell** [comment]
**PASSED**

- New openSSL
- new gem
```
Performed DownloadVVAManifestJob from Sidekiq(default) in 5349.45ms
```

<img width="845" alt="screen shot 2017-10-17 at 9 15 59 am" src="https://user-images.githubusercontent.com/18075411/31666887-d019ca0c-b31b-11e7-80b1-7fbfb5a93e85.png">
