### ISSUE TITLE
SPIKE: figure out what to do with outdated OpenSSL

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/connect_vva#9]
Reference: https://github.com/department-of-veterans-affairs/connect_vva/pull/8

**Comment by aroltsch** [comment]
Tested EX prod instance connectivity to the VVA production server and SSL handshake works. The reason being our EX prod instance uses an older version of OpenSSL: OpenSSL 1.0.1k-fips 8 Jan 2015. The DH key too small error was turned on in 2015. 

Problem: once AWS updates OpenSSL on our instances, VVA connectivity will break.

**Comment by aroltsch** [comment]
Waiting on the response from the VVA team.

**Comment by aroltsch** [comment]
Latest response on June 29, 2017

Nicholas /Alan,
 
My apologies that no one has gotten back to you before this. We were unexpectedly slammed with audit findings from an IRS FTI audit we just went through which required our full attention.  We are also in the middle of obtaining an ATO for our program. However from this point forward we will be on top of this.
 
We are now doing some analysis to determine how best to address the problem. At this point our Hardware is scheduled to be refreshed which will bring us up to-date and will address this issue.  We are looking to deploy that solution within the next month or two.
Additionally, we are working with our vendor Oracle, investigating if we can fix our current environment and if that would yield a faster solution.
 
Suren and Di two of top Architects and Admins are running with this.  I believed Suren reached out this afternoon to Alan for some additional information. If we have any additional questions we will reach out to Alan. We will plan to provide you an update on our progress by Wednesday July 5th.
 
Thanks,

Wayne

**Comment by aroltsch** [comment]
Response on JUly 5, 2017

Nicholas,
 
O&M have reviewed our options in addressing the issue.  We will be upgrading our WebLogic infrastructure and Java to address the “Key” Issue.
At this point we are looking at being able to deliver a solution in the Production Environment at the end of November 2017. This is a draft estimate and management may have additional input given a number of priorities we addressing during this timeline.
 
Next step, we will get with the Development Team since they may need to recompile and test code.  Their tasks could also add to the overall timeline that I mentioned.
 
Let me know if you have any questions.

Wayne

**Comment by aroltsch** [comment]
Closing this for now.

**Comment by askldjd** [comment]
Workaround is here: https://github.com/department-of-veterans-affairs/appeals-deployment/issues/693
